// Review & Rating action types
export const GET_REVIEWS_REQUEST = "GET_REVIEWS_REQUEST";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_FAILURE = "GET_REVIEWS_FAILURE";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAILURE = "CREATE_REVIEW_FAILURE";

export const GET_RATINGS_REQUEST = "GET_RATINGS_REQUEST";
export const GET_RATINGS_SUCCESS = "GET_RATINGS_SUCCESS";
export const GET_RATINGS_FAILURE = "GET_RATINGS_FAILURE";

export const CREATE_RATING_REQUEST = "CREATE_RATING_REQUEST";
export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS";
export const CREATE_RATING_FAILURE = "CREATE_RATING_FAILURE";

export const CLEAR_REVIEW_STATE = "CLEAR_REVIEW_STATE";
