export const FETCH_BLOGS_REQUEST = "FETCH_BLOGS_REQUEST";
export const FETCH_BLOGS_SUCCESS = "FETCH_BLOGS_SUCCESS";
export const FETCH_BLOGS_FAILURE = "FETCH_BLOGS_FAILURE";

export const FETCH_BLOG_DETAIL_REQUEST = "FETCH_BLOG_DETAIL_REQUEST";
export const FETCH_BLOG_DETAIL_SUCCESS = "FETCH_BLOG_DETAIL_SUCCESS";
export const FETCH_BLOG_DETAIL_FAILURE = "FETCH_BLOG_DETAIL_FAILURE";