// Blog action types for API integration
export const FETCH_BLOGS_REQUEST = "FETCH_BLOGS_REQUEST";
export const FETCH_BLOGS_SUCCESS = "FETCH_BLOGS_SUCCESS";
export const FETCH_BLOGS_FAILURE = "FETCH_BLOGS_FAILURE";

export const FETCH_BLOG_DETAIL_REQUEST = "FETCH_BLOG_DETAIL_REQUEST";
export const FETCH_BLOG_DETAIL_SUCCESS = "FETCH_BLOG_DETAIL_SUCCESS";
export const FETCH_BLOG_DETAIL_FAILURE = "FETCH_BLOG_DETAIL_FAILURE";

export const SEARCH_BLOGS_REQUEST = "SEARCH_BLOGS_REQUEST";
export const SEARCH_BLOGS_SUCCESS = "SEARCH_BLOGS_SUCCESS";
export const SEARCH_BLOGS_FAILURE = "SEARCH_BLOGS_FAILURE";

export const CLEAR_BLOG_DETAIL = "CLEAR_BLOG_DETAIL";
